const crypto=require('node:crypto');
const bcrypt=require('bcryptjs');
const User=require('../models/User');
const PasswordResetToken=require('../models/PasswordResetToken');
const {asyncHandler}=require('../middleware/errorHandler');
const {signToken}=require('../middleware/auth');
const emailRe=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const publicUser=u=>({id:u._id,name:u.name,email:u.email,role:u.role,createdAt:u.createdAt});
function validateCredentials(body,{signup=false}={}){if(!body||typeof body!=='object')return 'Invalid request';if(signup&&(!body.name||body.name.trim().length<2))return 'Name is required';if(!emailRe.test(String(body.email||'')))return 'Please enter a valid email';if(String(body.password||'').length<8)return 'Password must be at least 8 characters';if(signup&&body.password!==body.confirmPassword)return 'Passwords do not match';return null;}
const register=asyncHandler(async(req,res)=>{const msg=validateCredentials(req.body,{signup:true});if(msg)return res.status(400).json({success:false,message:msg});const email=req.body.email.trim().toLowerCase();if(await User.exists({email}))return res.status(409).json({success:false,message:'An account with that email already exists'});const hash=await bcrypt.hash(req.body.password,12);const user=await User.create({name:req.body.name.trim(),email,passwordHash:hash});res.status(201).json({success:true,data:{user:publicUser(user),token:signToken(user,true)}});});
const login=asyncHandler(async(req,res)=>{const msg=validateCredentials(req.body);if(msg)return res.status(400).json({success:false,message:msg});const user=await User.findOne({email:req.body.email.trim().toLowerCase()}).select('+passwordHash');if(!user||!(await bcrypt.compare(req.body.password,user.passwordHash)))return res.status(401).json({success:false,message:'Invalid email or password'});res.json({success:true,data:{user:publicUser(user),token:signToken(user,!!req.body.remember)}});});
const updateMe=asyncHandler(async(req,res)=>{const name=String(req.body?.name||'').trim();if(name.length<2)return res.status(400).json({success:false,message:'Name is required'});req.user.name=name;await req.user.save();res.json({success:true,data:{user:publicUser(req.user)}});});
const changePassword=asyncHandler(async(req,res)=>{const current=String(req.body?.currentPassword||'');const next=String(req.body?.newPassword||'');if(next.length<8)return res.status(400).json({success:false,message:'New password must be at least 8 characters'});const user=await User.findById(req.userId).select('+passwordHash');if(!await bcrypt.compare(current,user.passwordHash))return res.status(400).json({success:false,message:'Current password is incorrect'});user.passwordHash=await bcrypt.hash(next,12);await user.save();res.json({success:true,message:'Password changed successfully'});});
const me=asyncHandler(async(req,res)=>res.json({success:true,data:{user:publicUser(req.user)}}));
const logout=asyncHandler(async(req,res)=>res.json({success:true,message:'Logged out successfully'}));
const forgotPassword=asyncHandler(async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase();if(emailRe.test(email)){const user=await User.findOne({email});if(user){const raw=crypto.randomBytes(32).toString('hex');await PasswordResetToken.deleteMany({userId:user._id});await PasswordResetToken.create({userId:user._id,tokenHash:crypto.createHash('sha256').update(raw).digest('hex'),expiresAt:new Date(Date.now()+30*60*1000)});if(process.env.NODE_ENV!=='production')console.log(`Password reset token for ${email}: ${raw}`);}}res.json({success:true,message:'If an account exists, password reset instructions have been created.'});});
const resetPassword=asyncHandler(async(req,res)=>{const token=String(req.body?.token||'');const password=String(req.body?.password||'');if(token.length<20||password.length<8)return res.status(400).json({success:false,message:'Invalid reset request'});const hash=crypto.createHash('sha256').update(token).digest('hex');const record=await PasswordResetToken.findOne({tokenHash:hash});if(!record)return res.status(400).json({success:false,message:'Reset link is invalid or expired'});const user=await User.findById(record.userId);if(!user)return res.status(400).json({success:false,message:'Reset link is invalid or expired'});user.passwordHash=await bcrypt.hash(password,12);await user.save();await PasswordResetToken.deleteOne({_id:record._id});res.json({success:true,message:'Password reset successfully'});});
module.exports={register,login,me,updateMe,changePassword,logout,forgotPassword,resetPassword};
