const FormSchema=require('../models/FormSchema');const {asyncHandler}=require('../middleware/errorHandler');
const normalize=f=>{const o=f.toObject?f.toObject():f;if((!o.fields||!o.fields.length)&&o.sections?.length)o.fields=o.sections.flatMap(s=>s.fields||[]);if(!o.sections?.length)o.sections=[{title:'Form',description:'',order:0,fields:o.fields||[]}];return o;};
function canAccess(f,user){return !f.createdBy||String(f.createdBy)===String(user._id)||user.role==='admin';}
const list=asyncHandler(async(req,res)=>{const forms=await FormSchema.find({$or:[{createdBy:null},{createdBy:req.userId}]}).sort({updatedAt:-1});res.json({success:true,data:forms.map(normalize)});});
const getForm=asyncHandler(async(req,res)=>{const f=await FormSchema.findOne({formId:req.params.formId});if(!f||!canAccess(f,req.user))return res.status(404).json({success:false,message:'Form not found'});res.json({success:true,data:normalize(f)});});
const createForm=asyncHandler(async(req,res)=>{if(!req.body?.formId||!req.body?.title)return res.status(400).json({success:false,message:'formId and title are required'});if(await FormSchema.exists({formId:req.body.formId}))return res.status(409).json({success:false,message:'formId already exists'});const form=await FormSchema.create({...req.body,createdBy:req.userId});res.status(201).json({success:true,data:normalize(form)});});
const updateForm=asyncHandler(async(req,res)=>{const old=await FormSchema.findOne({formId:req.params.formId});if(!old||!canAccess(old,req.user))return res.status(404).json({success:false,message:'Form not found'});const nextVersion=(old.version||1)+1;const form=await FormSchema.findOneAndUpdate({formId:req.params.formId},{...req.body,formId:old.formId,createdBy:old.createdBy,version:nextVersion},{new:true,runValidators:true});res.json({success:true,data:normalize(form)});});
const duplicateForm=asyncHandler(async(req,res)=>{const source=await FormSchema.findOne({formId:req.params.formId});if(!source||!canAccess(source,req.user))return res.status(404).json({success:false,message:'Form not found'});const base=`${source.formId}-copy`;let formId=base;let n=2;while(await FormSchema.exists({formId}))formId=`${base}-${n++}`;const copy=await FormSchema.create({...source.toObject(),_id:undefined,isNew:true,formId,title:`${source.title} Copy`,version:1,createdBy:req.userId,createdAt:undefined,updatedAt:undefined});res.status(201).json({success:true,data:normalize(copy)});});
const deleteForm=asyncHandler(async(req,res)=>{const f=await FormSchema.findOne({formId:req.params.formId});if(!f||!canAccess(f,req.user))return res.status(404).json({success:false,message:'Form not found'});await f.deleteOne();res.json({success:true,message:'Form deleted'});});
module.exports={list,getForm,createForm,updateForm,duplicateForm,deleteForm};
