const Submission=require('../models/Submission');const FormSchema=require('../models/FormSchema');const {validateResponses,calculateProgress}=require('../utils/validateAgainstSchema');const {asyncHandler}=require('../middleware/errorHandler');
async function getForm(formId){const f=await FormSchema.findOne({formId});if(!f) {const e=new Error('Form not found');e.statusCode=404;throw e;}return f;}
const create=asyncHandler(async(req,res)=>{const f=await getForm(req.body.formId);const values=validateResponses(req.body.values||{},f,false);const s=await Submission.create({userId:req.userId,formId:f.formId,formVersion:f.version,formSnapshot:{formId:f.formId,title:f.title,description:f.description,version:f.version,fields:f.fields,sections:f.sections},values,aiAssistedFields:Array.isArray(req.body.aiAssistedFields)?req.body.aiAssistedFields.filter(x=>f.fields.some(y=>y.name===x)):[],currentStep:Number(req.body.currentStep)||0});res.status(201).json({success:true,data:s});});
const list=asyncHandler(async(req,res)=>{const q={userId:req.userId};if(req.query.status&&['draft','submitted','under_review','completed'].includes(req.query.status))q.status=req.query.status;const rows=await Submission.find(q).sort({updatedAt:-1}).limit(200);res.json({success:true,data:rows});});
const get=asyncHandler(async(req,res)=>{const s=await Submission.findOne({_id:req.params.id,userId:req.userId});if(!s)return res.status(404).json({success:false,message:'Submission not found'});res.json({success:true,data:s});});
const update=asyncHandler(async(req,res)=>{const s=await Submission.findOne({_id:req.params.id,userId:req.userId});if(!s)return res.status(404).json({success:false,message:'Submission not found'});if(s.status!=='draft')return res.status(400).json({success:false,message:'Only drafts can be edited'});const f=s.formSnapshot||await getForm(s.formId);const values=validateResponses(req.body.values===undefined?s.values:req.body.values,f,false);if(req.body.currentStep!==undefined)s.currentStep=Math.max(0,Number(req.body.currentStep)||0);s.values=values;s.aiAssistedFields=Array.isArray(req.body.aiAssistedFields)?req.body.aiAssistedFields.filter(x=>f.fields.some(y=>y.name===x)):s.aiAssistedFields;await s.save();res.json({success:true,data:{...s.toObject(),progress:calculateProgress(values,f)}});});
const remove=asyncHandler(async(req,res)=>{const s=await Submission.findOneAndDelete({_id:req.params.id,userId:req.userId,status:'draft'});if(!s)return res.status(404).json({success:false,message:'Draft not found'});res.json({success:true,message:'Draft deleted'});});
const submit=asyncHandler(async(req,res)=>{const s=await Submission.findOne({_id:req.params.id,userId:req.userId});if(!s)return res.status(404).json({success:false,message:'Submission not found'});if(s.status!=='draft')return res.status(400).json({success:false,message:'Submission is already finalized'});const f=s.formSnapshot||await getForm(s.formId);const values=validateResponses(s.values,f,true);s.values=values;s.status='submitted';s.submittedAt=new Date();await s.save();res.json({success:true,data:s});});
module.exports={create,list,get,update,remove,submit};
